//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
            this.ProductAttributeLookups = new HashSet<ProductAttributeLookup>();
        }
    
        public int ProdCatId { get; set; }
        public string CategoryName { get; set; }

        
        public virtual ICollection<Product> Products { get; set; }

        
        public virtual ICollection<ProductAttributeLookup> ProductAttributeLookups { get; set; }
    }
}
